name: "Host Ace Archive artifacts"
description: >
  This action is part of the Ace Archive project, and is used to host content
  submitted to Ace Archive.
inputs:
  path-glob:
    description: >
      A shell glob for matching artifact files in the repository. The action
      assumes that the second-to-last path component (the directory name) is
      the URL slug of the artifact.
    required: true
    default: "content/archive/*/index.md"
  w3s-token:
    description: >
      The secret API token for Web3.Storage. If this is provided, all artifacts
      in the repository are uploaded to Web3.Storage.
    required: false
  ipfs-api:
    description: >
      The multiaddr of the API endpoint of the running IPFS node. This is
      required to upload artifacts to Web3.Storage.
    required: false
  pin-endpoint:
    description: >
      The URL of the IPFS pinning service API endpoint to use. If this is
      provided, all artifacts in the repository are pinned using this pinning
      service.
    required: false
  pin-token:
    description: >
      The bearer token for the configured IPFS pinning service. This is
      required to pin artifacts using an IPFS pinning service.
    required: false
outputs:
  artifacts:
    description: >
      A JSON document describing the artifacts in the repository.
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "archive"
  color: "purple"
